# Generated by Django 2.0.6 on 2018-06-22 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilard_blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='postview',
            name='image_post',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post image/bilard_blog/media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.TextField(),
        ),
    ]
