# Generated by Django 2.0.6 on 2018-06-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilard_blogs', '0002_auto_20180622_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.AlterField(
            model_name='postview',
            name='image_post',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
