# Generated by Django 2.0.6 on 2018-06-22 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilard_blogs', '0003_auto_20180622_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_Joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
