# Generated by Django 2.0.6 on 2018-06-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilard_blogs', '0004_author_date_joined'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
